version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '08:37'
      timezone: Europe/Zurich
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      storybook:
        patterns:
          - '@storybook/*'
          - storybook
      javascript-tooling:
        patterns:
          - '@babel/*'
          - '@jest/*'
          - babel-*
          - eslint*
          - jest*
          - lerna
          - prettier

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '08:52'
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
